In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
jai = pd.read_csv('RawData/jaipur.csv')
jai.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,AU Small Finance Bank,4.4,"Banking , 10k-50k Employees , Fortune India 50..."
1,1,Teleperformance,3.8,"BPO , 50k-1 Lakh Employees , Forbes Global 200..."
2,2,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
4,4,HDFC Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."

In [4]:
jai.info()

<class 'pandas.DataFrame'>
RangeIndex: 8600 entries, 0 to 8599
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      8600 non-null   int64
 1   company_name    8600 non-null   str
 2   company_rating  8573 non-null   float64
 3   other_data      8600 non-null   str
dtypes: float64(1), int64(1), str(2)
memory usage: 713.8 KB

In [5]:
jai.shape

(8600, 4)

In [6]:
jai.shape

(8600, 4)

In [7]:
jai.describe()

        Unnamed: 0  company_rating
count  8600.000000     8573.000000
mean   4299.500000        3.943789
std    2482.750491        0.976650
min       0.000000        1.000000
25%    2149.750000        3.600000
50%    4299.500000        4.100000
75%    6449.250000        4.700000
max    8599.000000        5.000000

In [8]:
jai.isna().sum()

Unnamed: 0         0
company_name       0
company_rating    27
other_data         0
dtype: int64

In [13]:
jai['company_rating'] = jai['company_rating'].fillna(jai['company_rating'].mean() , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\1963221099.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  jai['company_rating'] = jai['company_rating'].fillna(jai['company_rating'].mean() , inplace=True)

In [14]:
jai.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    0
other_data        0
dtype: int64

In [15]:
jai.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    0
other_data        0
dtype: int64

In [16]:
jai.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,AU Small Finance Bank,4.4,"Banking , 10k-50k Employees , Fortune India 50..."
1,1,Teleperformance,3.8,"BPO , 50k-1 Lakh Employees , Forbes Global 200..."
2,2,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
4,4,HDFC Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."

In [17]:
jai.duplicated().sum()

np.int64(0)

In [18]:
rating = jai[jai['company_rating'] >= 4.0]

In [19]:
rating

,Unnamed: 0,company_name,company_rating,other_data
0,0,AU Small Finance Bank,4.4,"Banking , 10k-50k Employees , Fortune India 50..."
3,3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
4,4,HDFC Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
5,5,Hero MotoCorp,4.2,"Automobile , 5k-10k Employees , Public , 40 ye..."
6,6,Deutsche Bank,4.0,"Banking , 10k-50k Employees , Fortune India 50..."
...,...,...,...,...
8594,8594,Blue King,5.0,"1-10 Employees , Jaipur"
8595,8595,Between The Brews,5.0,Jaipur
8596,8596,National Helpline for Senior Citizens,4.2,Agartala +5 more
8598,8598,Jain Clave Polytech,4.0,Jaipur
8599,8599,Aagman Fitness Gym,4.5,Jaipur

In [36]:
jai.drop(columns='Unnamed: 0' , inplace=True)

In [37]:
jai.head(5)

,company_name,company_rating,other_data
0,AU Small Finance Bank,4.4,"Banking , 10k-50k Employees , Fortune India 50..."
1,Teleperformance,3.8,"BPO , 50k-1 Lakh Employees , Forbes Global 200..."
2,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
4,HDFC Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."

In [39]:
ahm =pd.read_csv('RawData/ahmedabad.csv')
ahm.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,Zydus Lifesciences,4.2,"Pharma , 10k-50k Employees , Public , 72 years..."
1,1,Intas Pharmaceuticals,4.2,"Pharma , 10k-50k Employees , Fortune India 500..."
2,2,Vodafone Idea,4.2,"Telecom , 5k-10k Employees , Public , 6 years ..."
3,3,TTEC India,3.8,"BPO , 1k-5k Employees , Public , 40 years old ..."
4,4,Cadila Pharmaceuticals,3.6,"Pharma , 5k-10k Employees , Public , 73 years ..."

In [40]:
ahm.shape

(10000, 4)

In [41]:
ahm.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10000 non-null  int64
 1   company_name    10000 non-null  str
 2   company_rating  9980 non-null   float64
 3   other_data      10000 non-null  str
dtypes: float64(1), int64(1), str(2)
memory usage: 931.3 KB

In [42]:
ahm.describe()

        Unnamed: 0  company_rating
count  10000.00000     9980.000000
mean    4999.50000        3.866483
std     2886.89568        0.854464
min        0.00000        1.000000
25%     2499.75000        3.500000
50%     4999.50000        4.000000
75%     7499.25000        4.400000
max     9999.00000        5.000000

In [43]:
ahm.isna().sum()

Unnamed: 0         0
company_name       0
company_rating    20
other_data         0
dtype: int64

In [45]:
ahm['company_rating']= ahm['company_rating'].fillna(ahm['company_rating'].mean() , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\3296274880.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  ahm['company_rating']= ahm['company_rating'].fillna(ahm['company_rating'].mean() , inplace=True)

In [46]:
ahm.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    0
other_data        0
dtype: int64

In [47]:
ahm.drop(columns=['Unnamed: 0'] , inplace=True)

In [50]:
ahm.duplicated().sum()

np.int64(1684)

In [51]:
ahm.head(5)

,company_name,company_rating,other_data
0,Zydus Lifesciences,4.2,"Pharma , 10k-50k Employees , Public , 72 years..."
1,Intas Pharmaceuticals,4.2,"Pharma , 10k-50k Employees , Fortune India 500..."
2,Vodafone Idea,4.2,"Telecom , 5k-10k Employees , Public , 6 years ..."
3,TTEC India,3.8,"BPO , 1k-5k Employees , Public , 40 years old ..."
4,Cadila Pharmaceuticals,3.6,"Pharma , 5k-10k Employees , Public , 73 years ..."

In [52]:
ban = pd.read_csv('RawData/bangalore.csv')
ban.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [53]:
ban.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    0
other_data        0
dtype: int64

In [54]:
ban.drop(columns=['Unnamed: 0'] , inplace=True)

In [55]:
ban.duplicated().sum()

np.int64(8375)

In [59]:
ban.shape

(8560, 3)

In [60]:
ban.groupby('company_name')['company_rating'].mean()

company_name
Accenture                  4.0
Amazon                     4.1
Axis Bank                  3.9
Capgemini                  3.8
Cognizant                  3.9
Concentrix Corporation     3.9
Genpact                    3.9
HCLTech                    3.7
HDB Financial Services     4.0
HDFC Bank                  4.0
IBM                        4.1
ICICI Bank                 4.0
Infosys                    3.8
Jio                        4.0
Larsen & Toubro Limited    4.1
Reliance Retail            4.0
TCS                        3.8
Tech Mahindra              3.7
Teleperformance            3.8
Wipro                      3.8
Name: company_rating, dtype: float64

In [61]:
ban.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [62]:
che = pd.read_csv('RawData/chennai.csv')
che.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [63]:
che.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    7
other_data        0
dtype: int64

In [64]:
che['company_rating'] = che['company_rating'].fillna(che['company_rating'].mean() , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\1697475907.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  che['company_rating'] = che['company_rating'].fillna(che['company_rating'].mean() , inplace=True)

In [65]:
che.duplicated().sum()

np.int64(0)

In [67]:
che.drop(columns=['Unnamed: 0'] , inplace=True)

In [68]:
che.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [73]:
che.groupby('company_name')['company_rating'].mean()

company_name
10decoders                    3.6
1CloudHub                     4.0
1point1 Solutions             3.4
20Cube Logistics              4.0
24x7 Hi Res Services          3.9
                             ...
tekVizion                     5.0
thinkbridge                   3.9
uLektz Learning Solutions     3.6
vThink Global Technologies    4.1
vTitan                        3.9
Name: company_rating, Length: 8262, dtype: float64

In [74]:
che.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [75]:
che.groupby('company_name')['company_rating'].max()

company_name
10decoders                    3.6
1CloudHub                     4.0
1point1 Solutions             3.4
20Cube Logistics              4.0
24x7 Hi Res Services          3.9
                             ...
tekVizion                     5.0
thinkbridge                   3.9
uLektz Learning Solutions     3.6
vThink Global Technologies    4.1
vTitan                        3.9
Name: company_rating, Length: 8262, dtype: float64

In [76]:
che.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [77]:
gur = pd.read_csv('RawData/gurugram.csv')
gur.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [78]:
gur.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    0
other_data        0
dtype: int64

In [79]:
gur.drop(columns=['Unnamed: 0'] , inplace=True)

In [80]:
gur.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [81]:
hyd = pd.read_csv('RawData/hyderabad.csv')
hyd.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [82]:
hyd.isna().sum()

Unnamed: 0         0
company_name       0
company_rating    10
other_data         0
dtype: int64

In [84]:
hyd['company_rating'] = hyd['company_rating'].fillna(hyd['company_rating'].mean() ,inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\2771381710.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  hyd['company_rating'] = hyd['company_rating'].fillna(hyd['company_rating'].mean() ,inplace=True)

In [85]:
hyd.drop(columns=['Unnamed: 0'] , inplace=True)

In [86]:
hyd.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [87]:
ind = pd.read_csv('RawData/indore.csv')
ind.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,Teleperformance,3.8,"BPO , 50k-1 Lakh Employees , Forbes Global 200..."
1,1,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,Cipla,4.1,"Pharma , 10k-50k Employees , Public , 89 years..."
3,3,TaskUs,3.5,"BPO , 5k-10k Employees , 16 years old , Indore..."
4,4,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."

In [88]:
ind.isna().sum()

Unnamed: 0         0
company_name       0
company_rating    17
other_data         0
dtype: int64

In [89]:
ind['company_rating'] = ind['company_rating'].fillna(ind['company_rating'] , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\3608648317.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  ind['company_rating'] = ind['company_rating'].fillna(ind['company_rating'] , inplace=True)

In [90]:
ind.drop(columns=['Unnamed: 0'] , inplace=True)

In [91]:
ind.head(5)

,company_name,company_rating,other_data
0,Teleperformance,3.8,"BPO , 50k-1 Lakh Employees , Forbes Global 200..."
1,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,Cipla,4.1,"Pharma , 10k-50k Employees , Public , 89 years..."
3,TaskUs,3.5,"BPO , 5k-10k Employees , 16 years old , Indore..."
4,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."

In [92]:
mum = pd.read_csv('RawData/mumbai.csv')
mum.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Kotak Mahindra Bank,3.9,"Banking , 50k-1 Lakh Employees , Public , 21 y..."
2,2,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
4,4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [93]:
mum.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    5
other_data        0
dtype: int64

In [101]:
mum['company_rating'] = mum['company_rating'].fillna(mum['company_rating'] , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\2754104084.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  mum['company_rating'] = mum['company_rating'].fillna(mum['company_rating'] , inplace=True)

In [102]:
mum.head(5)

,company_name,company_rating,other_data,company_rating\t
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,...",3.8
1,Kotak Mahindra Bank,3.9,"Banking , 50k-1 Lakh Employees , Public , 21 y...",3.9
2,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,...",4.0
3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year...",4.0
4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,...",3.8

In [103]:
mum.isna().sum()

company_name        0
company_rating      5
other_data          0
company_rating\t    5
dtype: int64

In [104]:
mum['company_rating'] = mum['company_rating'].fillna(mum['company_rating'].mean() , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\652449158.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  mum['company_rating'] = mum['company_rating'].fillna(mum['company_rating'].mean() , inplace=True)

In [105]:
mum.drop(columns=['company_rating\t'] , inplace=True)

In [106]:
mum.isna().sum()

company_name      0
company_rating    0
other_data        0
dtype: int64

In [107]:
mum.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Kotak Mahindra Bank,3.9,"Banking , 50k-1 Lakh Employees , Public , 21 y..."
2,Accenture,4.0,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,ICICI Bank,4.0,"Banking , 1 Lakh+ Employees , Public , 30 year..."
4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [108]:
noi = pd.read_csv('RawData/noida.csv')
noi.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,iEnergizer,4.7,"BPO , 10k-50k Employees , 24 years old , Noida..."
1,1,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Tech Mahindra,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [109]:
noi.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    5
other_data        0
dtype: int64

In [110]:
noi['company_rating'] = noi['company_rating'].fillna(noi['company_rating'].mean() , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\674100024.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  noi['company_rating'] = noi['company_rating'].fillna(noi['company_rating'].mean() , inplace=True)

In [111]:
noi.drop(columns=['Unnamed: 0'] , inplace=True)

In [112]:
noi.head(5)

,company_name,company_rating,other_data
0,iEnergizer,4.7,"BPO , 10k-50k Employees , 24 years old , Noida..."
1,HCLTech,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,Genpact,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Tech Mahindra,3.7,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [113]:
pun = pd.read_csv('RawData/pune.csv')
pun.head(5)

,Unnamed: 0,company_name,company_rating,other_data
0,0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,1,Infosys,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,2,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,3,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [114]:
pun.isna().sum()

Unnamed: 0        0
company_name      0
company_rating    7
other_data        0
dtype: int64

In [115]:
pun['company_rating'] = pun['company_rating'].fillna(pun['company_rating'].mean() , inplace=True)

C:\Users\singh\AppData\Local\Temp\ipykernel_2516\3603888635.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  pun['company_rating'] = pun['company_rating'].fillna(pun['company_rating'].mean() , inplace=True)

In [116]:
pun.drop(columns=['Unnamed: 0'] , inplace=True)

In [117]:
pun.head(5)

,company_name,company_rating,other_data
0,TCS,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
1,Infosys,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
2,Cognizant,3.9,"IT Services & Consulting , 1 Lakh+ Employees ,..."
3,Wipro,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."
4,Capgemini,3.8,"IT Services & Consulting , 1 Lakh+ Employees ,..."

In [118]:
import pandas as pd
import os

# Map every single city dataframe variable to its respective city display name
city_dfs = {
    'Ahmedabad': ahm,
    'Bangalore': ban,
    'Chennai': che,
    'Gurugram': gur,
    'Hyderabad': hyd,
    'Indore': ind,      # Added Indore
    'Jaipur': jai,      # Added Jaipur
    'Mumbai': mum,
    'Noida': noi,
    'Pune': pun
}

combined_list = []

for city_name, df in city_dfs.items():
    # Create a copy to prevent SettingWithCopyWarning
    temp_df = df.copy()
    
    # Drop index column if it exists
    if 'Unnamed: 0' in temp_df.columns:
        temp_df.drop(columns=['Unnamed: 0'], inplace=True)
        
    # Assign the city name column
    temp_df['city'] = city_name
    
    combined_list.append(temp_df)

# Concatenate all into a single master dataframe
master_df = pd.concat(combined_list, ignore_index=True)

# Clean rating column to ensure numeric values
master_df['company_rating'] = pd.to_numeric(master_df['company_rating'], errors='coerce')
master_df['company_rating'] = master_df['company_rating'].fillna(master_df['company_rating'].median())

# Fill remaining missing text values
master_df.fillna('N/A', inplace=True)

# Save to processed folder
os.makedirs('processed_data', exist_ok=True)
output_path = 'processed_data/master_ambitionbox.csv'
master_df.to_csv(output_path, index=False)

print(f"Master file successfully created at {output_path} with {len(master_df)} rows across {master_df['city'].nunique()} cities!")
display(master_df.head())

Master file successfully created at processed_data/master_ambitionbox.csv with 94580 rows across 10 cities!

,company_name,company_rating,other_data,city
0,Zydus Lifesciences,4.2,"Pharma , 10k-50k Employees , Public , 72 years...",Ahmedabad
1,Intas Pharmaceuticals,4.2,"Pharma , 10k-50k Employees , Fortune India 500...",Ahmedabad
2,Vodafone Idea,4.2,"Telecom , 5k-10k Employees , Public , 6 years ...",Ahmedabad
3,TTEC India,3.8,"BPO , 1k-5k Employees , Public , 40 years old ...",Ahmedabad
4,Cadila Pharmaceuticals,3.6,"Pharma , 5k-10k Employees , Public , 73 years ...",Ahmedabad